### ISSUE TITLE
Backpack overwrote other backpack

### ISSUE THREAD

**Issue by ionstorm66** [deletey/CompactStorage#137] opened 2022-09-08 02:16 UTC
I have 3 backpacks, white, magenta, and blue. I opened the white, closed it, then quickly opened the magenta. After that the whites contents and size overwrote the magenta. The magenta shrunk to the size of the white and got duplicated contents.

**Comment by witchica** [comment] 2022-09-08 06:53
Which version of the mod was this using?

**Comment by ionstorm66** [comment] 2022-09-08 20:31
compact_storage_fabric-5.0_lts_1.19.2

**Comment by LunafeyLazuli** [comment] 2023-01-17 14:46
Same issue has been happening on Forge as well for 1.18.2, and sometimes even the sizes get mixed up, or the bags will straight copy each other

**Comment by witchica** [comment] 2023-01-18 15:56
Can I ask if this behaviour is happening on a server or just singleplayer? I have never been able to replciate this so far

**Comment by witchica** [comment] 2023-01-18 16:23
I can't replicate it but have found the cause, the saving of backpack contents goes on player hand rather than the slot it was opened from eg: if you swap quickly enough that the server didn't keep up then it'll save after you open the new backpack - in your main hand. This has been fixed now and will be added into the other versions of the mod, will update with new versions when posted

**Closed as completed by witchica** 2023-01-18 16:24 UTC

**Comment by LunafeyLazuli** [comment] 2023-01-18 20:36
Sorry didn't see the reply sooner XD but for me at least it's happening on my server

**Comment by witchica** [comment] 2023-01-18 22:25
This should now be fixed in the following builds

Forge:

- [1.18.2](https://www.curseforge.com/minecraft/mc-mods/compactstorage/files/4352472)
- [1.19.2](https://www.curseforge.com/minecraft/mc-mods/compactstorage/files/4352445)
- [1.19.3](https://www.curseforge.com/minecraft/mc-mods/compactstorage/files/4352231)

Fabric:

- [1.18.2](https://www.curseforge.com/minecraft/mc-mods/compactstorage/files/4352618)
- [1.19.2](https://www.curseforge.com/minecraft/mc-mods/compactstorage/files/4352575)
- [1.19.3](https://www.curseforge.com/minecraft/mc-mods/compactstorage/files/4352637)

Let me know if the issue persists, hoping that fixed it
