### ISSUE TITLE
Items not connecting to Compact Chests.

### ISSUE THREAD

**Issue by TorinnTheDragon** [deletey/CompactStorage#71] opened 2019-04-21 14:05 UTC
This issue just now showing up on update 3.1 where all the compact chests is not accepting any inventory other than manually imputing and hoppers.  Basically any item that auto extracts, for example Ender IO's Item Conduit or Mekanism's Logistical Transporter) from a chest won't connect to any compact chest. VOD of what I'm explaining about https://youtu.be/dWMQxzbbMKk .  I forgot to say that it worked before.

**Comment by Shadows-of-Fire** [comment] 2019-04-22 17:47
CompactStorage chests will not work with most modded objects without use of ComPatchedStorage to add the item handler capability.

**Comment by TorinnTheDragon** [comment] 2019-04-22 19:43
> 
> 
> CompactStorage chests will not work with most modded objects without use of ComPatchedStorage to add the item handler capability.

Thanks for the information I let the person know to use this on their next update of their pack.

**Comment by witchica** [comment] 2019-04-26 18:09
This will be added into the base mod within the next 24 hours.

**Comment by Shadows-of-Fire** [comment] 2019-04-26 18:53
This is technically a duplicate of #65 and could be closed in favor of it.

**Comment by witchica** [comment] 2019-04-26 19:04
Fixed in https://github.com/deletey/CompactStorage/commit/cba0432c51d85f5d40c272ba9dbd5d02d9bcfe88

**Closed as completed by witchica** 2019-04-26 19:04 UTC
